name: APRoP Dispatcher

on:
  pull_request:
    types: [ closed ]

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Dump context
      uses: crazy-max/ghaction-dump-context@v1
    - name: APRoP Notify Parent
      if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
      run: |
        REPOSHORT="$(echo $GITHUB_REPOSITORY | sed 's#.*/##g')"
        echo "pull request succeeded, will take action here"; \
        curl -s -X POST https://api.github.com/repos/hid-gs/${{ secrets.WA_PARENT_REPO }}/dispatches \
        -H 'Accept: application/vnd.github.v3+json' \
        -u ${{ secrets.ACCESS_TOKEN }} \
        --data '{"event_type": "aprop-pr-merged", "client_payload": { "repository": "'"$REPOSHORT"'", "sha": "'"$GITHUB_SHA"'"     }}'

