name: Auto PR on Parent Repo Dispatcher

on:
  push:
    branches:
      - main
      - master
  repository_dispatch:

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Auto PR On Parent
      if: github.event.pull_request.merged == 'true'
      run: |
        echo "pull request succeeded, would have taken action here"

