name: Auto PR on Parent Repo Dispatcher

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
    types: [ closed ]

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Always run
      run: |
        echo "${{ github.event.pull_request.merged }}"
        echo "${{ github.event.pull_request.merged }}"
        env | sort
    - name: Auto PR On Parent
      if: github.event.pull_request.merged == 'true'
      run: |
        echo "pull request succeeded, would have taken action here"

